### PR TITLE
#20 rsym

### PR DESCRIPTION
**Pull request by holyjak**
to simplify searching for function calls

### CODE REVIEW

**Comment by holyjak** [comment]
sorry, will fix the undesired whitespace changes

**Comment by borkdude** [comment]
The added var must also be made available in the native binary:

https://github.com/borkdude/grasp/blob/3fa99aedd0594c0ae958de7d25d8900992f60ca5/src/grasp/native.clj#L71

**Comment by holyjak** [comment]
Thanks a lot for fixing the native! I would get to it eventually but this way it was much faster :)

**Comment by borkdude** [comment]
No problem, it turned out to be a bit harder than I thought :)

**Pull request merged**
